# GUI test: run ffconv with its FFCONV_TEST_* hooks and check what it produced.
# Usage: cmake -DFFCONV=<exe> -DOUT_DIR=<dir>
#              -DMODE=<empty|shot|convert|options|greyed|fixed|preview|preview_zoom|filters|filters_bad>
#              [-DINPUT=<file>]
#              -P ui_test.cmake
# (opens real windows: only registered when CONV_GUI_TESTS is ON)

set(shot "${OUT_DIR}/ui_test_${MODE}.png")
file(REMOVE "${shot}")
set(ENV{FFCONV_TEST_SHOT} "${shot}")
if(INPUT)
    set(ENV{FFCONV_TEST_INPUT} "${INPUT}")
endif()

if(MODE STREQUAL "convert" OR MODE STREQUAL "options" OR MODE STREQUAL "filters")
    set(out "${OUT_DIR}/ui_test_${MODE}.mp4")
    set(done "${OUT_DIR}/ui_test_${MODE}_done.png")
    set(json "${OUT_DIR}/ui_test_${MODE}.json")
    file(REMOVE "${out}" "${done}" "${json}")
    set(ENV{FFCONV_TEST_CONTAINER} "mp4")
    set(ENV{FFCONV_TEST_STREAMS} "0=libx264,1=aac,2=mov_text")
    set(ENV{FFCONV_TEST_OUTPUT} "${out}")
    set(ENV{FFCONV_TEST_CONVERT} "1")
    set(ENV{FFCONV_TEST_DONE_SHOT} "${done}")
    set(ENV{FFCONV_TEST_JOB_JSON} "${json}")
endif()
if(MODE STREQUAL "options")
    # set through the option dialogs' widgets, as a user would
    set(ENV{FFCONV_TEST_OPTIONS} "0:crf=30;0:preset=veryfast;0:bf=2;0:profile=main;1:b=96k;mux:movflags=+faststart")
    set(ENV{FFCONV_TEST_OPTIONS_SHOT} "${OUT_DIR}/ui_test_options_dialog.png")
endif()

if(MODE STREQUAL "filters" OR MODE STREQUAL "filters_bad")
    # through the filter dialogs: a list for the video, text for the audio
    set(ffile "${OUT_DIR}/ui_test_${MODE}_filters.txt")
    set(states "${OUT_DIR}/ui_test_${MODE}_states.txt")
    file(REMOVE "${ffile}" "${states}")
    set(ENV{FFCONV_TEST_CONTAINER} "mp4")
    set(ENV{FFCONV_TEST_STREAMS} "0=libx264,1=aac,2=mov_text")
    set(ENV{FFCONV_TEST_OPTIONS} "0:preset=ultrafast")
    set(ENV{FFCONV_TEST_FILTERS_SHOT} "${OUT_DIR}/ui_test_${MODE}_dialog.png")
    set(ENV{FFCONV_TEST_FILTERS_FILE} "${ffile}")
    set(ENV{FFCONV_TEST_STATES_FILE} "${states}")
    if(MODE STREQUAL "filters")
        set(ENV{FFCONV_TEST_FILTERS} "0:scale:w=640:h=-2;0:hflip")
        set(ENV{FFCONV_TEST_FILTER_TEXT} "1:volume=0.5,aresample=44100")
    else()
        # crop wider than the scaled picture: refused when the chain is set up
        set(ENV{FFCONV_TEST_FILTERS} "0:scale:w=640:h=-2;0:hflip;0:crop:w=4000")
        set(ENV{FFCONV_TEST_OUTPUT} "${OUT_DIR}/ui_test_${MODE}.mp4")
    endif()
endif()

if(MODE STREQUAL "greyed" OR MODE STREQUAL "fixed")
    # test.mkv chosen for Matroska (every stream copied), then AVI: the
    # choices must stay as they are, greyed out where AVI cannot take them
    set(states "${OUT_DIR}/ui_test_${MODE}_states.txt")
    file(REMOVE "${states}")
    set(ENV{FFCONV_TEST_CONTAINER} "avi")
    set(ENV{FFCONV_TEST_OUTPUT} "${OUT_DIR}/ui_test_${MODE}.avi")
    set(ENV{FFCONV_TEST_STATES_FILE} "${states}")
    if(MODE STREQUAL "greyed")
        set(ENV{FFCONV_TEST_STREAMS} "2=libopus")            # AVI cannot store Opus
    else()
        set(ENV{FFCONV_TEST_STREAMS} "2=aac,3=drop")         # what AVI can take
    endif()
endif()

if(MODE STREQUAL "preview" OR MODE STREQUAL "preview_zoom")
    # libx265 at 4.5 s, through the preview window
    set(pshot "${OUT_DIR}/ui_test_${MODE}_window.png")
    file(REMOVE "${pshot}")
    set(ENV{FFCONV_TEST_CONTAINER} "mp4")
    set(ENV{FFCONV_TEST_STREAMS} "0=libx265,1=aac,2=mov_text")
    set(ENV{FFCONV_TEST_OPTIONS} "0:crf=30;0:preset=ultrafast")
    set(ENV{FFCONV_TEST_PREVIEW} "4.5")
    set(ENV{FFCONV_TEST_PREVIEW_SHOT} "${pshot}")
    if(MODE STREQUAL "preview_zoom")
        # 400 %, on the edge of the checkerboard where the line crosses it
        set(ENV{FFCONV_TEST_PREVIEW_ZOOM} "4")
        set(ENV{FFCONV_TEST_PREVIEW_PAN} "0.66,0.62")
    endif()
endif()

execute_process(COMMAND "${FFCONV}" RESULT_VARIABLE rc TIMEOUT 180)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "ffconv exited with ${rc}")
endif()
if(NOT EXISTS "${shot}")
    message(FATAL_ERROR "no window snapshot was written")
endif()
if(MODE STREQUAL "convert" OR MODE STREQUAL "options" OR MODE STREQUAL "filters")
    if(NOT EXISTS "${done}")
        message(FATAL_ERROR "the conversion did not finish")
    endif()
    file(SIZE "${out}" size)
    if(size LESS 100000)
        message(FATAL_ERROR "output is missing or too small (${size} bytes)")
    endif()
endif()
function(expect_lines file)
    file(READ "${file}" got)
    foreach(line ${ARGN})
        string(FIND "${got}" "${line}" pos)
        if(pos LESS 0)
            message(FATAL_ERROR "expected \"${line}\" in ${file}:\n${got}")
        endif()
    endforeach()
endfunction()
if(MODE STREQUAL "filters")
    expect_lines("${ffile}" "#0 scale on ok" "#1 hflip on ok" "text scale=w=640:h=-2,hflip"
                 "text (custom) volume=0.5,aresample=44100" "chain ok")
    expect_lines("${states}" "convert enabled")
    expect_lines("${json}" [["name": "scale"]] [["w": "640"]] [["name": "hflip"]]
                 [["filters": "volume=0.5,aresample=44100"]])
endif()
if(MODE STREQUAL "filters_bad")
    expect_lines("${ffile}" "#0 scale on ok" "#1 hflip on ok" "#2 crop on error: Invalid too big" "chain error: crop: Invalid too big")
    expect_lines("${states}" "convert disabled")
endif()
if(MODE STREQUAL "greyed" OR MODE STREQUAL "fixed")
    file(READ "${states}" got)
    if(MODE STREQUAL "greyed")
        set(expected "selected container avi" "selected #3 copy" "selected #2 transcode libopus"
                     "convert disabled" "action#3 off Copy | avi cannot store subrip"
                     "encoder#2 off libopus | avi cannot store opus"
                     "container off avi" "container on  matroska")
    else()
        set(expected "selected container avi" "selected #2 transcode aac" "selected #3 drop"
                     "convert enabled" "container on  avi")
    endif()
    foreach(line ${expected})
        string(FIND "${got}" "${line}" pos)
        if(pos LESS 0)
            message(FATAL_ERROR "expected \"${line}\" in:\n${got}")
        endif()
    endforeach()
endif()
if((MODE STREQUAL "preview" OR MODE STREQUAL "preview_zoom") AND NOT EXISTS "${pshot}")
    message(FATAL_ERROR "the preview was not rendered")
endif()
if(MODE STREQUAL "options")
    # the job the widgets produced...
    file(READ "${json}" job)
    foreach(expected [["crf": "30"]] [["preset": "veryfast"]] [["bf": "2"]] [["profile": "main"]]
                     [["b": "96k"]] [["movflags": "faststart"]])
        string(FIND "${job}" "${expected}" pos)
        if(pos LESS 0)
            message(FATAL_ERROR "the job lacks ${expected}:\n${job}")
        endif()
    endforeach()
    # ...and what x264 says it used (its settings are stored in the stream)
    file(STRINGS "${out}" sei REGEX "x264 - core" LIMIT_COUNT 1)
    foreach(expected "crf=30.0" "subme=2" "bframes=2")
        string(FIND "${sei}" "${expected}" pos)
        if(pos LESS 0)
            message(FATAL_ERROR "x264 did not use ${expected}")
        endif()
    endforeach()
endif()
