# GUI test: run ffconv with its FFCONV_TEST_* hooks and check what it produced.
# Usage: cmake -DFFCONV=<exe> -DOUT_DIR=<dir> -DMODE=<shot|convert> [-DINPUT=<file>] -P ui_test.cmake
# (opens real windows: only registered when CONV_GUI_TESTS is ON)

set(shot "${OUT_DIR}/ui_test_${MODE}.png")
file(REMOVE "${shot}")
set(ENV{FFCONV_TEST_SHOT} "${shot}")
if(INPUT)
    set(ENV{FFCONV_TEST_INPUT} "${INPUT}")
endif()

if(MODE STREQUAL "convert")
    set(out "${OUT_DIR}/ui_test_out.mp4")
    set(done "${OUT_DIR}/ui_test_done.png")
    file(REMOVE "${out}" "${done}")
    set(ENV{FFCONV_TEST_CONTAINER} "mp4")
    set(ENV{FFCONV_TEST_STREAMS} "0=libx264,1=aac,2=mov_text")
    set(ENV{FFCONV_TEST_OUTPUT} "${out}")
    set(ENV{FFCONV_TEST_CONVERT} "1")
    set(ENV{FFCONV_TEST_DONE_SHOT} "${done}")
endif()

execute_process(COMMAND "${FFCONV}" RESULT_VARIABLE rc TIMEOUT 180)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "ffconv exited with ${rc}")
endif()
if(NOT EXISTS "${shot}")
    message(FATAL_ERROR "no window snapshot was written")
endif()
if(MODE STREQUAL "convert")
    if(NOT EXISTS "${done}")
        message(FATAL_ERROR "the conversion did not finish")
    endif()
    file(SIZE "${out}" size)
    if(size LESS 100000)
        message(FATAL_ERROR "output is missing or too small (${size} bytes)")
    endif()
endif()
