# GUI test: run ffconv with its FFCONV_TEST_* hooks and check what it produced.
# Usage: cmake -DFFCONV=<exe> -DOUT_DIR=<dir> -DMODE=<empty|shot|convert|options> [-DINPUT=<file>]
#              -P ui_test.cmake
# (opens real windows: only registered when CONV_GUI_TESTS is ON)

set(shot "${OUT_DIR}/ui_test_${MODE}.png")
file(REMOVE "${shot}")
set(ENV{FFCONV_TEST_SHOT} "${shot}")
if(INPUT)
    set(ENV{FFCONV_TEST_INPUT} "${INPUT}")
endif()

if(MODE STREQUAL "convert" OR MODE STREQUAL "options")
    set(out "${OUT_DIR}/ui_test_${MODE}.mp4")
    set(done "${OUT_DIR}/ui_test_${MODE}_done.png")
    set(json "${OUT_DIR}/ui_test_${MODE}.json")
    file(REMOVE "${out}" "${done}" "${json}")
    set(ENV{FFCONV_TEST_CONTAINER} "mp4")
    set(ENV{FFCONV_TEST_STREAMS} "0=libx264,1=aac,2=mov_text")
    set(ENV{FFCONV_TEST_OUTPUT} "${out}")
    set(ENV{FFCONV_TEST_CONVERT} "1")
    set(ENV{FFCONV_TEST_DONE_SHOT} "${done}")
    set(ENV{FFCONV_TEST_JOB_JSON} "${json}")
endif()
if(MODE STREQUAL "options")
    # set through the option dialogs' widgets, as a user would
    set(ENV{FFCONV_TEST_OPTIONS} "0:crf=30;0:preset=veryfast;0:bf=2;0:profile=main;1:b=96k;mux:movflags=+faststart")
    set(ENV{FFCONV_TEST_OPTIONS_SHOT} "${OUT_DIR}/ui_test_options_dialog.png")
endif()

if(MODE STREQUAL "greyed" OR MODE STREQUAL "fixed")
    # test.mkv chosen for Matroska (every stream copied), then AVI: the
    # choices must stay as they are, greyed out where AVI cannot take them
    set(states "${OUT_DIR}/ui_test_${MODE}_states.txt")
    file(REMOVE "${states}")
    set(ENV{FFCONV_TEST_CONTAINER} "avi")
    set(ENV{FFCONV_TEST_OUTPUT} "${OUT_DIR}/ui_test_${MODE}.avi")
    set(ENV{FFCONV_TEST_STATES_FILE} "${states}")
    if(MODE STREQUAL "greyed")
        set(ENV{FFCONV_TEST_STREAMS} "2=libopus")            # AVI cannot store Opus
    else()
        set(ENV{FFCONV_TEST_STREAMS} "2=aac,3=drop")         # what AVI can take
    endif()
endif()

execute_process(COMMAND "${FFCONV}" RESULT_VARIABLE rc TIMEOUT 180)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "ffconv exited with ${rc}")
endif()
if(NOT EXISTS "${shot}")
    message(FATAL_ERROR "no window snapshot was written")
endif()
if(MODE STREQUAL "convert" OR MODE STREQUAL "options")
    if(NOT EXISTS "${done}")
        message(FATAL_ERROR "the conversion did not finish")
    endif()
    file(SIZE "${out}" size)
    if(size LESS 100000)
        message(FATAL_ERROR "output is missing or too small (${size} bytes)")
    endif()
endif()
if(MODE STREQUAL "greyed" OR MODE STREQUAL "fixed")
    file(READ "${states}" got)
    if(MODE STREQUAL "greyed")
        set(expected "selected container avi" "selected #3 copy" "selected #2 transcode libopus"
                     "convert disabled" "action#3 off Copy | avi cannot store subrip"
                     "encoder#2 off libopus | avi cannot store opus"
                     "container off avi" "container on  matroska")
    else()
        set(expected "selected container avi" "selected #2 transcode aac" "selected #3 drop"
                     "convert enabled" "container on  avi")
    endif()
    foreach(line ${expected})
        string(FIND "${got}" "${line}" pos)
        if(pos LESS 0)
            message(FATAL_ERROR "expected \"${line}\" in:\n${got}")
        endif()
    endforeach()
endif()
if(MODE STREQUAL "options")
    # the job the widgets produced...
    file(READ "${json}" job)
    foreach(expected [["crf": "30"]] [["preset": "veryfast"]] [["bf": "2"]] [["profile": "main"]]
                     [["b": "96k"]] [["movflags": "faststart"]])
        string(FIND "${job}" "${expected}" pos)
        if(pos LESS 0)
            message(FATAL_ERROR "the job lacks ${expected}:\n${job}")
        endif()
    endforeach()
    # ...and what x264 says it used (its settings are stored in the stream)
    file(STRINGS "${out}" sei REGEX "x264 - core" LIMIT_COUNT 1)
    foreach(expected "crf=30.0" "subme=2" "bframes=2")
        string(FIND "${sei}" "${expected}" pos)
        if(pos LESS 0)
            message(FATAL_ERROR "x264 did not use ${expected}")
        endif()
    endforeach()
endif()
